- name: Setup yum repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbiMQ ansd Erlang
  ansible.builtin.yum:
    - rabbitmq-server
    - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm

- name: Start RabbitMQ
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Set up application user in Rabbit mq
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags:
      - administrator
