- name: setup repofile for Nodejs
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install node js
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download app code
  ansible.builtin.import_role:
    name: common
    tasks_from:  download

- name: Clean the old app code
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy app code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
